#platform :ios, “6.0”
#pod ‘Reachability’, ‘~> 3.0.0’
#pod ‘RegexKitLite’
#pod 'WebViewJavascriptBridge', '~> 4.1.5'
pod 'Masonry', '~> 1.0.0’
pod 'MBProgressHUD', '~> 0.9.2'
pod 'FMDB', '~> 2.6.2'
pod 'AFNetworking'
pod 'MJRefresh'
pod 'TAOverlay'
pod 'MJExtension'